// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.rooinaction.coursemanager.model.Payment;
import org.rooinaction.coursemanager.model.PaymentDataOnDemand;
import org.rooinaction.coursemanager.model.PaymentIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PaymentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PaymentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PaymentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PaymentIntegrationTest: @Transactional;
    
    @Autowired
    PaymentDataOnDemand PaymentIntegrationTest.dod;
    
    @Test
    public void PaymentIntegrationTest.testCountPayments() {
        Assert.assertNotNull("Data on demand for 'Payment' failed to initialize correctly", dod.getRandomPayment());
        long count = Payment.countPayments();
        Assert.assertTrue("Counter for 'Payment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PaymentIntegrationTest.testFindPayment() {
        Payment obj = dod.getRandomPayment();
        Assert.assertNotNull("Data on demand for 'Payment' failed to initialize correctly", obj);
        Integer id = obj.getIdpayment();
        Assert.assertNotNull("Data on demand for 'Payment' failed to provide an identifier", id);
        obj = Payment.findPayment(id);
        Assert.assertNotNull("Find method for 'Payment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Payment' returned the incorrect identifier", id, obj.getIdpayment());
    }
    
    @Test
    public void PaymentIntegrationTest.testFindAllPayments() {
        Assert.assertNotNull("Data on demand for 'Payment' failed to initialize correctly", dod.getRandomPayment());
        long count = Payment.countPayments();
        Assert.assertTrue("Too expensive to perform a find all test for 'Payment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Payment> result = Payment.findAllPayments();
        Assert.assertNotNull("Find all method for 'Payment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Payment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PaymentIntegrationTest.testFindPaymentEntries() {
        Assert.assertNotNull("Data on demand for 'Payment' failed to initialize correctly", dod.getRandomPayment());
        long count = Payment.countPayments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Payment> result = Payment.findPaymentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Payment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Payment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PaymentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Payment' failed to initialize correctly", dod.getRandomPayment());
        Payment obj = dod.getNewTransientPayment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Payment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Payment' identifier to be null", obj.getIdpayment());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Payment' identifier to no longer be null", obj.getIdpayment());
    }
    
    @Test
    public void PaymentIntegrationTest.testRemove() {
        Payment obj = dod.getRandomPayment();
        Assert.assertNotNull("Data on demand for 'Payment' failed to initialize correctly", obj);
        Integer id = obj.getIdpayment();
        Assert.assertNotNull("Data on demand for 'Payment' failed to provide an identifier", id);
        obj = Payment.findPayment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Payment' with identifier '" + id + "'", Payment.findPayment(id));
    }
    
}
